### ISSUE TITLE
.abc format unknown

### ISSUE THREAD

**Issue by ahmadhasan2k8** [alicevision/qmlAlembic#3]
Hello,
I have built AliceVision and trying to run Meshroom to see the output. I can run till the SfM part but whenever I run PrepareDenseScene from the UI, I get error and the log is below:
```
Program called with the following parameters:
 * input = "/tmp/MeshroomCache/StructureFromMotion/1791bc36ef6221756d0020876349789a691bd297/sfm.abc"
 * output = "/tmp/MeshroomCache/PrepareDenseScene/4e7505e5bff4c13bdaf8439604ad549d2dc7314c"
 * verboseLevel = "info"

[14:17:29.879224][error] Unknown input SfM data format: '.abc'
[14:17:29.879249][error] The input SfMData file '/tmp/MeshroomCache/StructureFromMotion/1791bc36ef6221756d0020876349789a691bd297/sfm.abc' cannot be read.
```
Looking at the log it looks like it's related to Alembic and I have built qmlAlembic successfully and put the install prefix in my path already. But I still get this error. Could you please take a look?

Thanks,
Ahmad

**Comment by fabiencastan** [comment]
It's probably because you have built AliceVision without Alembic.

The qmlAlembic plugin is only for visualization in Meshroom and has no link with your error in the pipeline computation.

**Comment by ahmadhasan2k8** [comment]
I see. That's possible. I'll try again and get back to you.

**Comment by ahmadhasan2k8** [comment]
That solved it. Thank you.
