### ISSUE TITLE
ubuntu 16.04 Add Qml Plugin error?

### ISSUE THREAD

**Issue by happyfrank** [alicevision/qmlAlembic#9]
**Hello I already build & install this plugin.**

`ubuntu@ubuntu-4DAGE:~/alicevision/deps/qmlAlembic/build$ make -j8
[ 14%] Automatic moc for target alembicEntityQmlPlugin
Generating moc_AlembicEntity.cpp
Generating moc_BaseAlembicObject.cpp
Generating moc_CameraLocatorEntity.cpp
Generating moc_PointCloudEntity.cpp
Generating moc_plugin.cpp
[ 14%] Built target alembicEntityQmlPlugin_automoc
Scanning dependencies of target alembicEntityQmlPlugin
[ 28%] Building CXX object src/CMakeFiles/alembicEntityQmlPlugin.dir/BaseAlembicObject.cpp.o
[ 42%] Building CXX object src/CMakeFiles/alembicEntityQmlPlugin.dir/CameraLocatorEntity.cpp.o
[ 57%] Building CXX object src/CMakeFiles/alembicEntityQmlPlugin.dir/AlembicEntity.cpp.o
[ 71%] Building CXX object src/CMakeFiles/alembicEntityQmlPlugin.dir/PointCloudEntity.cpp.o
[ 85%] Building CXX object src/CMakeFiles/alembicEntityQmlPlugin.dir/alembicEntityQmlPlugin_automoc.cpp.o
[100%] Linking CXX shared library libalembicEntityQmlPlugin.so
[100%] Built target alembicEntityQmlPlugin
ubuntu@ubuntu-4DAGE:~/alicevision/deps/qmlAlembic/build$ make install
[ 14%] Automatic moc for target alembicEntityQmlPlugin
[ 14%] Built target alembicEntityQmlPlugin_automoc
[100%] Built target alembicEntityQmlPlugin
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /home/ubuntu/alicevision/install/qml/AlembicEntity/qmldir
-- Installing: /home/ubuntu/alicevision/install/qml/AlembicEntity/libalembicEntityQmlPlugin.so
-- Set runtime path of "/home/ubuntu/alicevision/install/qml/AlembicEntity/libalembicEntityQmlPlugin.so" to ""
`

**and set the the path in ~/.bashrc** 

`export QML2_IMPORT_PATH=/home/ubuntu/alicevision/install/qml:$QML2_IMPORT_PATH`

But when I run **Meshroom** I don't have this plugin. 
![sfm](https://user-images.githubusercontent.com/12987532/45987621-28b6b700-c0a5-11e8-8e22-6ec31c3c6449.png)

**Comment by yann-lty** [comment]
Do you have Alembic libraries in your LD_LIBRARY_PATH when starting Meshroom? The plugin relies on them and won't load if not.
You can use the environment variable [QT_DEBUG_PLUGINS](http://doc.qt.io/qt-5/deployment-plugins.html#debugging-plugins) to get more info on plugin loading at startup and see if it does try to load it and why it fails.

**Comment by happyfrank** [comment]
Dear @yann-lty thank you very much. It works. ^v^
